name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: packages
      run: sudo apt install docbook-to-man

    - name: build
      run: cd src && make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
